# Generated by Django 5.0.6 on 2024-05-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomrate',
            name='room_id',
            field=models.IntegerField(),
        ),
    ]
