# Generated by Django 5.0.6 on 2024-05-26 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_management', '0002_alter_discount_discount_id_alter_roomrate_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='overriddenroomrate',
            name='overridden_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='overriddenroomrate',
            name='room_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrided_rate', to='rate_management.roomrate'),
        ),
    ]
